### ISSUE TITLE
Allow Configuration Subcomponents to be specified as other files

### ISSUE THREAD

**Issue by ieichen137** [EmersonElectricCo/lowball#8]
Our current configuration structure works very well, but this will add a lot more flexibility to the configuration models, and allow configuration file reuse for different shared subcomponents. 

This would support something like this. The file format supported should include both yaml and json as with the main config file. 

```

meta: /path/to/metaconf.yaml
application: /path/to/applicationconf.yaml
authentication: 
  max_token_life: 6000
logging: 
  logger: yes
auth_provider: /path/to/auth_conf.yaml
auth_db: /path/to/auth_db.yaml


```

In this scenario, the configuration loader should handle the discovery and opening of the files at those locations, and treat them the same as if it were defined under the main application file.
